name: release

on:
  push:
    tags:
      - "*"

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc
    outputs:
      version: ${{ steps.prep.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Project ${{ steps.prep.outputs.version }}
          body_path: .CurrentChangelog.md
          draft: true
          prerelease: false

  build_ubuntu_latest:
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/upload-artifact@v1
      with:
        name: build-latest
        path: ./build/ubuntu-latest.tar.gz

  download_artifact_ubuntu_latest:
    runs-on: ubuntu-latest
    needs: [create, build_ubuntu_latest]
    container:
      image: wasmedge/wasmedge:ubuntu-build-gcc

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build-latest

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./ubuntu-latest

    - name: Upload files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create.outputs.upload_url }}
        asset_path: ./build-latest/ubuntu-latest.tar.gz
        asset_name: Project-${{ needs.create.outputs.version }}.ubuntu-latest.tar.gz
        asset_content_type: application/x-gzip

  build_manylinux2014:
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/upload-artifact@v1
      with:
        name: build-manylinux2014
        path: ./build/ubuntu-manylinux2014.tar.gz

  download_artifact_manylinux2014_x86_64:
    runs-on: ubuntu-latest
    needs: [create, build_manylinux2014]
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build-manylinux2014

    - name: Display structure of downloaded file
      run: ls -alhR ./build-manylinux2014

    - name: Upload files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create.outputs.upload_url }}
        asset_path: ./build-manylinux2014/ubuntu-manylinux2014.tar.gz
        asset_name: Project-${{ needs.create.outputs.version }}.ubuntu-manylinux2014.tar.gz
        asset_content_type: application/x-gzip

  build_manylinux2010:
    runs-on: ubuntu-latest
    needs: create
    container:
      image: wasmedge/wasmedge:manylinux2010_x86_64

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - uses: actions/upload-artifact@v1
      with:
        name: build-manylinux2010
        path: ./build/ubuntu-manylinux2010.tar.gz

  download_artifact_manylinux2010_x86_64:
    runs-on: ubuntu-latest
    needs: [create, build_manylinux2010]
    steps:
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v1
      with:
        name: build-manylinux2010

    - name: Display structure of downloaded file
      run: ls -alhR ./build-manylinux2010

    - name: Upload files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create.outputs.upload_url }}
        asset_path: ./build-manylinux2010/ubuntu-manylinux2010.tar.gz
        asset_name: Project-${{ needs.create.outputs.version }}.ubuntu-manylinux2010.tar.gz
        asset_content_type: application/x-gzip

  build_manylinux1:
    needs: create
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:manylinux1_x86_64

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - uses: actions/upload-artifact@v1
      with:
        name: build-manylinux1
        path: ./build/ubuntu-manylinux1.tar.gz

  download_artifact_manylinux1_x86_64:
    runs-on: ubuntu-latest
    needs: [create, build_manylinux1]
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build-manylinux1

    - name: Display structure of downloaded file
      run: ls -alhR ./build-manylinux1

    - name: Upload files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create.outputs.upload_url }}
        asset_path: ./build-manylinux1/ubuntu-manylinux1.tar.gz
        asset_name: Project-${{ needs.create.outputs.version }}.ubuntu-manylinux1.tar.gz
        asset_content_type: application/x-gzip
